### ISSUE TITLE
Reduce verbose / loudness when running a minimiser in a notebook

### ISSUE THREAD

**Issue by andreufont** [CobayaSampler/cobaya#148]
Hi again - When I run the minimiser (default settings) in a Jupyter notebook, I get a fairly long list of output lines about the progress of the minimiser. In my tests, the minimiser takes a few seconds, but it is enough to really polute my nice, tidy notebooks :-)

It is possible to make the minimiser quiter? I tried looking at the documentation, but it wasn't trivial. I also tried guessing things like "silence=True", "debug=False", "verbose=False", but none of these wild guesses did the trick. 

Thanks for the great work!

**Comment by andreufont** [comment]
For BOBYQA, I'm guessing this could be done by specifying "print_progress=False" as a kwarg when we call "solve". Not sure about scipy.

**Comment by JesusTorrado** [comment]
Should be fixed in the last commit. We were looking into to ways to solve this since we incorporated it (see https://github.com/numericalalgorithmsgroup/pybobyqa/issues/10) but they were not using the logging module, so it wasn't possible until the last version they have published.

Now prints nothing unless `debug: True` (unfortunately they don't provide an intermediate level for reporting progress).

**Comment by andreufont** [comment]
It works great, thanks!
