### ISSUE TITLE
Resuming with python_path

### ISSUE THREAD

**Issue by Pablo-Lemos** [CobayaSampler/cobaya#153]
I cannot resume chains that use an external theory code using the python_path argument. It seems like the chains do not store the python_path when saving

[input] {} (old) vs {‘python_path’: ‘/my/path/’} (new)

I would really appreciate some help with this!

**Comment by cmbant** [comment]
Does it help to save right yaml changing pop to get in LikelihoodCollection.__init__?

**Comment by JesusTorrado** [comment]
Ah, you meant popped in LikelihoodCollection.init. No that shouldn't 
happen: it should not overwrote anything in the input at init. If what 
Antony suggested is not enough, try adding the thing from my email.

**Comment by misharash** [comment]
If code modifications don't help with existing runs and you don't want to rerun them from the beginning, it's also possible to delete all `python_path` options from yaml config and move external code from previous `python_path` to one of common python library directories (e.g. `~/.local/lib/python3.?/site-packages` on linux). That's how I temporarily overcame #139. Making symlinks instead of moving also should work. However, this approach may create quite a mess.

**Comment by JesusTorrado** [comment]
Hi @misharash

For existing runs, I think going to the .updated.yaml and deleting *there* the python_path should be enough?

**Comment by Pablo-Lemos** [comment]
No that does not seem to work @JesusTorrado. In fact, it appears that even when you do not delete the python_path, the issue is that when it tries to resume it does not read the python_path line from the existing chains

**Comment by cmbant** [comment]
It should use the python path from your input file as long as it's set correctly there -  it seems to work for me with changes in https://github.com/CobayaSampler/cobaya/pull/152?
