### ISSUE TITLE
Resuming to get better convergence

### ISSUE THREAD

**Issue by cmbant** [CobayaSampler/cobaya#154]
If a run completes, and .checkpoint file says converged: true, re-starting with .yaml having decreased Rminus1_stop does nothing (still stops immediately saying converged, though obviously not correct with new option).

Can we just skip "converged" when doing this in sampler.py?

```
                    for k, v in checkpoint_info[kinds.sampler][self.get_name()].items():
                        setattr(self, k, v)
```

**Comment by JesusTorrado** [comment]
We have actually found a workaround during a MSc project here in Aachen: just make `converged: False` in the checkpoint.

Regarding ignoring it there, this would have the effect of needing to get to the next checkpoint before stopping if we try to resume with the **same** R-1, which is not nice.

Maybe ignoring it if the new R-1 is smaller? (in practice, smaller than Rminus1_last stored in the checkpoint)

**Comment by cmbant** [comment]
I don't see much of a problem continuing to the next checkpoint. eg. maybe the user wants to check that R-1 being reached is not a fluke (why would they be resuming if they didn't want at least some more samples?).

In sampler.py the code is general, so should not depend on specific parameters. We could compare the entire sampler input block, and set converged=F if any changes to parameters, but as currently organised we don't have access to the old info at the point of reading the checkpoint.

**Comment by JesusTorrado** [comment]
> I don't see much of a problem continuing to the next checkpoint. eg. 
> maybe the user wants to check that R-1 being reached is not a fluke (why 
> would they be resuming if they didn't want at least some more samples?).

Not always that you resume you want this behaviour, e.g. you may have a grid of model batch scripts that you submit to the cluster until all runs are converged, and prefer that the ones already converged are just ignored (run and exit immediately).

> In sampler.py the code is general, so should not depend on specific 
> parameters. We could compare the entire sampler input block, and set 
> converged=F if any changes to parameters, but as currently organised we 
> don't have access to the old info at the point of reading the checkpoint.

I agree with sampler.py being general. But actually, there is no converged=True check in sampler. This would be done in mcmc.initialise, so that converged is not ignored, but set to false if Rminus_last (from checkpoint) is larger than the given Rminus1 (which is always preferred to the updated.yaml, because is in the prefer_new list). Or am I missing something?

**Comment by JesusTorrado** [comment]
Just adding the following under the "sync_processes()" in mcmc.initialise works:

        # If resuming converged run with new lower Rminus1, ignore converged state
        if self.Rminus1_stop < self.Rminus1_last:
            self.log.info("Resuming converged run with stronger convergence criterion.")
            self.converged = False

**Comment by cmbant** [comment]
Sounds like it should work, though would also need to check other parameters as well (max_samples, Rminus1_cl_level,Rminus1_cl_stop,...), plus equivalent in e.g. polychord if needed.

**Comment by JesusTorrado** [comment]
It does work, but sure, needs more tests. And also defining behaviour: does resuming with already-reached max_samples stops automatically or re-run for that amount of steps? (not sure, but I think it is more intuitive to stop, so that if one wants 1000 more samples one needs to make max_samples not 1k but 1k+previous value?)

**Comment by cmbant** [comment]
Looks like checkpoint doesn't currently save Rminus1_cl_last, so don't think we have the information just from the checkpoint file. I tried to do something here https://github.com/CobayaSampler/cobaya/pull/157

I agree max_samples should be total.

**Comment by vivianmiranda** [comment]
That was something that caught my attention. Sometimes I wanted R-1 ~ 0.02 and then I changed to R-1 for refinement
