### ISSUE TITLE
Overriding chi2 = -2*lnlike

### ISSUE THREAD

**Issue by seshnadathur** [CobayaSampler/cobaya#169]
There are a few scenarios in which this relationship does not work. One is when the covariance matrix depends on the parameters being sampled over, so that the normalization factor is not the same at each point in the chain and can't be factored out. Another is when propagating the uncertainty in the estimated covariance matrix requires using a likelihood that is not purely Gaussian (as in [https://arxiv.org/abs/1511.05969](https://arxiv.org/abs/1511.05969)).

In these sorts of cases, the chi2 values that Cobaya deduces from the log likelihood and then appends to the chain are not useful (and can even be nonsensical, e.g. <0). Is there a way to tell Cobaya _not_ to add chi2 for a given likelihood to the chains? Or, if we add a derived parameter named `chi2__myLikelihood` can this override the automatically calculated value?

**Comment by cmbant** [comment]
You can still define an effective chi2 by this. ,Even in more complex cases it's usually possible to subtract a sensible constant so that the effective chi2 has roughly the usual interpretation, e.g. defining it so a "perfect" fit would have chi2=0  (the logpost is then not really a normalized log posterior of course..) I don't think there's currently any control over it, and indeed in some cases is not useful (there's often lots of other redundant columns in the chain outputs too).

**Comment by seshnadathur** [comment]
Through trial and error I found that defining some effective chi2 as a derived parameter with the name `chi2` or `chi2__[myLikelihoodName]` leads to an error as it conflicts with the existing columns. But a simple workaround is to just give it a slightly different name. And as you say, one can always ignore the additional redundant columns.
