### ISSUE TITLE
Using different instances of class

### ISSUE THREAD

**Issue by Xx-Luffy-xX** [CobayaSampler/cobaya#223]
I wish to run Cobaya with two different modified CLASS codes.
At the moment, I just replace the content of "classy" directory with one version or the other. But this way does not allow running both versions simultaneously.

Is there a way to change the default path to "classy"? Say, having "classy_1" and "classy_2" inside the "code" directory, and specifying which one to use in the input.yaml file?

Thanks.

**Comment by JesusTorrado** [comment]
Hi @Xx-Luffy-xX ,

You can place your modified CLASS versions anywhere, not necessarily in the `code` folder, and simply give `classy` in the input file the property `path` with the path to the version that you want to use. At initialisation, Cobaya will state where it is loading CLASS from in each case.

Closing, since not an issue. But please don't hesitate to keep updating us here if it doesn't work as expected.
