### ISSUE TITLE
Importance Sampling

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#28]
Hi - I couldn't find instruction to do importance sampling in Cobaya.

**Comment by JesusTorrado** [comment]
Hi Vivian,

No Importance yet, but working on it this week. There will be a prototype in branch `post` at some point in the following days. I'll let you know here when it is working/testable.

Is what you want to do just adding/removing likelihoods, or is there anything else you'd like it to do?

**Comment by vivianmiranda** [comment]
Hi Jesus,

No - usually I add terms in theory calculation (non-linear lensing) or change the halofit and see the differences. It would be important for my current project

Could you also make the update for the cobaya that does not depend on the new CAMB 1.0 - I can’t switch codes in the middle of my project because I am doing careful code comparison.

Best
Vivian

On May 8, 2019, at 10:12 PM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Vivian,

No Importance yet, but working on it this week. There will be a prototype in branch post at some point in the following days. I'll let you know here when it is working/testable.

Is what you want to do just adding/removing likelihoods, or is there anything else you'd like it to do?

**Comment by JesusTorrado** [comment]
Hi Vivian,

There is already a functional but incomplete version in branch `post`. As discussed, please switch to that branch fully (too many files have changed) and copy the camb.py from 1.0. Let me know here what does not work and I'll help you patch it.

An example input file is included below (call with `cobaya-run`; scripted call not implemented yet, but can do it quickly if needed right now). To force CAMB's recomputation with new settings, include the new CAMB's options under `post:add:theory`. Notice that for this to affect a likelihood in particular, you need to remove it and add it simultaneously (so that it's recomputed; non-mentioned likelihoods are not recomputed).

Also, notice that due to some code limitations right now, you need to specify what parameters belong to CAMB using the `theory_params:input_params` below. Hopefully, I'll find a way around that in the future.

Expect rough edges; just let me know. And, most of all, if any results looks wrong, let me know and we'll take a look at whether that's a bug. Suggestions on how to improve the input syntax are also welcomed. Good luck!

    # Path to the original sample
    output: chains/example
    # Path to the modules installation folder
    modules: /home/jesus/scratch/modules1.1
    
    post:
      # Suffix for saving chain (will be saved as [output]_post_[suffix]
      suffix: whatever
      # Integer for #lines or <1 for fraction of lines
      skip: 0
      # Integer: use only one every X samples
      thin: 1
      # TEMPORARY (BETA ONLY): theory parameters
      theory_params:
        input: ['As', 'ns', 'cosmomc_theta', 'ombh2', 'omch2', 'mnu', 'tau']
      # Adding stuff
      add:
        prior:
          # ...
        likelihood:
          # to recompute a likelihood, add it here AND under remove
        theory:
          # add here your theory code, if you want to recompute observables
          # affects only likelihoods that have been removed+added
          camb:
            path: whatever/CAMB
            extra_args:
              whatever: value
      # Removing stuff
      remove:
        prior:
          # ...
        likelihood:
          # ...

**Comment by JesusTorrado** [comment]
Adding/removing parameters works now in branch `post` (dynamical parameters for now; no theory parameters yet). Just add a `params` block under `add`/`remove`.

@vivianmiranda, did you have time to check if it works and does what's necessary for your case?

**Comment by JesusTorrado** [comment]
Hi @vivianmiranda 

Just to let you know about one change: the `theory_params` argument in the instructions above is not present anymore: instead, it will be automatically added to new chains. For post-processing older chains (your case), simply edit the `__full.yaml` to add an `input_params: [param1, etc]` to the `camb` block specifying the same input params as before.

Did you have time to test it?

**Comment by JesusTorrado** [comment]
Closing for now. Feel free to reopen if you find any unexpected error!
