### ISSUE TITLE
OpenMP

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#3]
This is more of a dream than an issue.

Not all code are thread-safe (CosmoLike for example it isn't) - and these code are getting so complex that making it thread-safe is a difficult task. On the other hand - threading can be quite useful. Is it possible to turn a feature so that Cobaya will use OpenMP to calculate more than one likelihood at the same time instead of threading each likelihood separately?

**Comment by JesusTorrado** [comment]
Hi Vivian,

Though it sounds very useful, but I am afraid it would be a nightmare for us the developers: as you said there are non-thread-safe codes, so we would need to know in advance which one is or isn't (and that would conflict with letting the user use an arbitrary unknown-to-us python function as a likelihood).

Our approach is to compute each likelihood sequentially, and rely on the likelihood authors to take advantage of OpenMP palletisation themselves in the internal of the likelihood computation. If done right, this should result in a similar performance to computing the likelihoods in parallel on different threads.

Does this answer your question? Is there a specific setting that you are finding yourself into (e.g. having to evaluate tens of different likelihoods), so that we may be able to find an alternative way to speed it up?

**Comment by vivianmiranda** [comment]
Yes - I know

Although the user could send a flag that shows if he wants Cobaya to use openmp or not - then Cobaya collects all likelihood that are flagged and run them in parallel. Of course this is wishful thinking in dreamland.

And yes it does. My specific setting is Cosmolike - it takes ~0.8 seconds to evaluate everything (PS: I don’t understand why the computation of \chi+- and gamma_t are in the likelihood and not into the theory classes that would allow them to be cached - if you split the IA integrals from example - even changing IA would be fast (maybe semi-fast like inflation) - then all multiplicative biases and IA could be considered “fast” - in cosmolike we create a separate cache to try to implement this strategy).

Best
Vivian

On Nov 12, 2018, at 7:13 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Vivian,

Though it sounds very useful, but I am afraid it would be a nightmare for us the developers: as you said there are non-thread-safe codes, so we would need to know in advance which one is or isn't (and that would conflict with letting the user use an arbitrary unknown-to-us python function as a likelihood).

Our approach is to compute each likelihood sequentially, and rely on the likelihood authors to take advantage of OpenMP palletisation themselves in the internal of the likelihood computation. If done right, this should result in a similar performance to computing the likelihoods in parallel on different threads.

Does this answer your question? Is there a specific setting that you are finding yourself into (e.g. having to evaluate tens of different likelihoods), so that we may be able to find an alternative way to speed it up?

**Comment by JesusTorrado** [comment]
If CosmoLike does internal caching, then this should be solved by specifying speeds for individual parameters (as opposed to per-likelihood speeds), which is precisely https://github.com/CobayaSampler/cobaya/issues/1

Keep an eye on it!

**Comment by cmbant** [comment]
The DES theory components are implemented in the DES code rather than in the theory at the moment because they make a bunch of non-general approximations (Limber, neglect RSD, etc..). It's a bit tricky in general to decide how to best split things up, but certainly agree this could be pulled out somehow.

**Comment by vivianmiranda** [comment]
He Prof Lewis,

That seems a good opportunity for collaboration, no? CosmoLike is not that fast (~0.8 s non thread) but very general - yours are quite fast and non-general. 

If we can make both that could have a big impact.

best
Vivian
