### ISSUE TITLE
Passing accuracy and source term params to CAMB

### ISSUE THREAD

**Issue by louisl3grand** [CobayaSampler/cobaya#393]
Hi Antony and Jesus, 

I would like to know if there is a way to pass [accuracy parameters](https://camb.readthedocs.io/en/latest/model.html#camb.model.AccuracyParams) and [source term parameters](https://camb.readthedocs.io/en/latest/model.html#camb.model.SourceTermParams) to CAMB.
Apologies if this already is explained somewhere, but I didn't find.

My naive approach would be to put that in the yaml parameter file like this:

```
theory:
  camb:
    extra_args:
      lens_potential_accuracy: 1
      Want_CMB: False
      Want_CMB_lensing: False
      NonLinear: NonLinear_both
      SourceTerms:
        limber_windows: True
        limber_phi_lmin: 300
        counts_lensing: true
        counts_density: true
```

But it returns the following error: 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[13], line 2
      1 t0 = time.time()
----> 2 logp = model.logpost(fiducials)
      3 print(f'Evaluated in {time.time()-t0:.2e} seconds')
      4 print(f'Log like value: {logp}')

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/model.py:589, in Model.logpost(self, params_values, make_finite, cached)
    572 def logpost(self,
    573             params_values: Union[Dict[str, float], Sequence[float]],
    574             make_finite: bool = False, cached: bool = True) -> float:
    575     """
    576     Takes an array or dictionary of sampled parameter values.
    577     If the argument is an array, parameters must have the same order as in the input.
   (...)
    587     could be reused.
    588     """
--> 589     return self.logposterior(params_values, make_finite=make_finite,
    590                              return_derived=False, cached=cached).logpost

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/model.py:558, in Model.logposterior(self, params_values, as_dict, make_finite, return_derived, cached, _no_check)
    555         logpriors.extend(self.prior.logps_external(input_params))
    556 if -np.inf not in logpriors:
    557     # noinspection PyUnboundLocalVariable
--> 558     like = self._loglikes_input_params(input_params,
    559                                        return_derived=return_derived,
    560                                        cached=cached, make_finite=make_finite)
    561     loglikes, derived_sampler = like if return_derived else (like, [])
    562 else:

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/model.py:378, in Model._loglikes_input_params(self, input_params, return_derived, return_output_params, as_dict, make_finite, cached)
    376 depend_list = [input_params[p] for p in param_dep]
    377 params = {p: input_params[p] for p in component.input_params}
--> 378 compute_success = component.check_cache_and_compute(
    379     params, want_derived=need_derived,
    380     dependency_params=depend_list, cached=cached)
    381 if not compute_success:
    382     loglikes[:] = -np.inf

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/theory.py:253, in Theory.check_cache_and_compute(self, params_values_dict, dependency_params, want_derived, cached)
    251     self.timer.start()
    252 try:
--> 253     if self.calculate(state, want_derived, **params_values_dict) is False:
    254         return False
    255 except always_stop_exceptions:

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/theories/camb/camb.py:1031, in CambTransfers.calculate(self, state, want_derived, **params_values_dict)
   1029 def calculate(self, state, want_derived=True, **params_values_dict):
   1030     # Set parameters
-> 1031     camb_params = self.cobaya_camb.set(params_values_dict, state)
   1032     # Failed to set parameters but no error raised
   1033     # (e.g. out of computationally feasible range): lik=0
   1034     if not camb_params:

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/theories/camb/camb.py:833, in CAMB.set(self, params_values_dict, state)
    831         base_args.pop(not_needed, None)
    832 self._reduced_extra_args = self.extra_args.copy()
--> 833 params = self.camb.set_params(**base_args)
    834 # pre-set the parameters that are not varying
    835 for non_param_func in ['set_classes', 'set_matter_power', 'set_for_lmax']:

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/camb/camb.py:178, in set_params(cp, verbose, **params)
    176     par = k
    177 if hasattr(obj, par):
--> 178     setattr(obj, par, params[k])
    179 else:
    180     raise CAMBUnknownArgumentError("Unrecognized parameter: %s" % k)

TypeError: expected SourceTermParams instance, got dict
```

So it seems that the SourceTerms parameters from the yaml file is passed on to CAMB, but it doesnt recognise it because it expects a SourceTermParams and not a dict. However from yaml I guess it is only possible to pass a dict ? 
Is the solution of this to modify the camb.py file in Cobaya to initialize CAMB with all the possible accuracy and source term parameters ?

**Comment by cmbant** [comment]
Off the top of my head, try

SourceTerms.limber_windows
Etc?

________________________________
From: Louis Legrand ***@***.***>
Sent: Friday, December 13, 2024 5:28:44 PM
To: CobayaSampler/cobaya ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CobayaSampler/cobaya] Passing accuracy and source term params to CAMB (Issue #393)


Hi Antony and Jesus,

I would like to know if there is a way to pass accuracy parameters<https://camb.readthedocs.io/en/latest/model.html#camb.model.AccuracyParams> and source term parameters<https://camb.readthedocs.io/en/latest/model.html#camb.model.AccuracyParams> to CAMB.
Apologies if this already is explained somewhere, but I didn't find.

My naive approach would be to put that in the yaml parameter file like this:

theory:
  camb:
    extra_args:
      lens_potential_accuracy: 1
      Want_CMB: False
      Want_CMB_lensing: False
      NonLinear: NonLinear_both
      SourceTerms:
        limber_windows: True
        limber_phi_lmin: 300
        counts_lensing: true
        counts_density: true


But it returns the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[13], line 2
      1 t0 = time.time()
----> 2 logp = model.logpost(fiducials)
      3 print(f'Evaluated in {time.time()-t0:.2e} seconds')
      4 print(f'Log like value: {logp}')

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/model.py:589, in Model.logpost(self, params_values, make_finite, cached)
    572 def logpost(self,
    573             params_values: Union[Dict[str, float], Sequence[float]],
    574             make_finite: bool = False, cached: bool = True) -> float:
    575     """
    576     Takes an array or dictionary of sampled parameter values.
    577     If the argument is an array, parameters must have the same order as in the input.
   (...)
    587     could be reused.
    588     """
--> 589     return self.logposterior(params_values, make_finite=make_finite,
    590                              return_derived=False, cached=cached).logpost

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/model.py:558, in Model.logposterior(self, params_values, as_dict, make_finite, return_derived, cached, _no_check)
    555         logpriors.extend(self.prior.logps_external(input_params))
    556 if -np.inf not in logpriors:
    557     # noinspection PyUnboundLocalVariable
--> 558     like = self._loglikes_input_params(input_params,
    559                                        return_derived=return_derived,
    560                                        cached=cached, make_finite=make_finite)
    561     loglikes, derived_sampler = like if return_derived else (like, [])
    562 else:

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/model.py:378, in Model._loglikes_input_params(self, input_params, return_derived, return_output_params, as_dict, make_finite, cached)
    376 depend_list = [input_params[p] for p in param_dep]
    377 params = {p: input_params[p] for p in component.input_params}
--> 378 compute_success = component.check_cache_and_compute(
    379     params, want_derived=need_derived,
    380     dependency_params=depend_list, cached=cached)
    381 if not compute_success:
    382     loglikes[:] = -np.inf

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/theory.py:253, in Theory.check_cache_and_compute(self, params_values_dict, dependency_params, want_derived, cached)
    251     self.timer.start()
    252 try:
--> 253     if self.calculate(state, want_derived, **params_values_dict) is False:
    254         return False
    255 except always_stop_exceptions:

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/theories/camb/camb.py:1031, in CambTransfers.calculate(self, state, want_derived, **params_values_dict)
   1029 def calculate(self, state, want_derived=True, **params_values_dict):
   1030     # Set parameters
-> 1031     camb_params = self.cobaya_camb.set(params_values_dict, state)
   1032     # Failed to set parameters but no error raised
   1033     # (e.g. out of computationally feasible range): lik=0
   1034     if not camb_params:

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/cobaya/theories/camb/camb.py:833, in CAMB.set(self, params_values_dict, state)
    831         base_args.pop(not_needed, None)
    832 self._reduced_extra_args = self.extra_args.copy()
--> 833 params = self.camb.set_params(**base_args)
    834 # pre-set the parameters that are not varying
    835 for non_param_func in ['set_classes', 'set_matter_power', 'set_for_lmax']:

File /opt/miniconda3/envs/cloe2p1/lib/python3.9/site-packages/camb/camb.py:178, in set_params(cp, verbose, **params)
    176     par = k
    177 if hasattr(obj, par):
--> 178     setattr(obj, par, params[k])
    179 else:
    180     raise CAMBUnknownArgumentError("Unrecognized parameter: %s" % k)

TypeError: expected SourceTermParams instance, got dict


So it seems that the SourceTerms parameters from the yaml file is passed on to CAMB, but it doesnt recognise it because it expects a SourceTermParams and not a dict. However from yaml I guess it is only possible to pass a dict ?
Is the solution of this to modify the camb.py file in Cobaya to initialize CAMB with all the possible accuracy and source term parameters ?

**Comment by louisl3grand** [comment]
Yes, indeed it is working, thanks a lot!
