### ISSUE TITLE
Dragging Problem

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#4]
Hi - Sorry for all the e-mails - but today is a day I am testing a lot of things in the interface.

I try the dragging method, and I am facing big problems. Here I have H0 (slow) and DES_m1 and DES_m2 (fast) - but the way Cobaya is evaluating them is making caching in CosmoLike impossible (or any cache whatsoever)

I made a screenshot that shows the value of H0 - going back and forth between 67.05 and 68.68 instead of fixing at 67.05 and then doing the drag oversampling (and only after switching to 68.68).

Many parameters are only fast slow after being cached (i.e. is fast if you run multiple times with fixed cosmo because the CAMB/CosmoLike from the last time you changed slow is cached on memory) and if you are changing slow at every point - then there is no fast, right? There is something I am losing in this dragging scheme...(or do you just cache all the products of all precious points and not just the last time slow parameters changed)?

<img width="196" alt="screen shot 2018-11-12 at 3 39 20 pm" src="https://user-images.githubusercontent.com/3210728/48379546-b1a7a300-e691-11e8-9cc0-8f7d79d9538d.png">

**Comment by JesusTorrado** [comment]
Hi Vivian,

Dragging works by simulating a simultaneous jump in slow+fast space by proposing a slow jump first and then a series of small fast substeps in each of which an interpolation of the likelihood is used. For each interpolation, the theory code is called twice -- once per extreme of the jump (but this is fast, since the theory code results are cached). That's why it appears to jump back and forth in H0 in your case. The details are here: https://arxiv.org/abs/1304.447

I understand how this can spoil your internal caching in CosmoLike. A possible workaround can be what we do in Cobaya to make dragging efficient: have your code caching the last 2 states (2 sets of results) instead of just the last one.
