### ISSUE TITLE
CAMB Fail

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#6]
Hi

Is there an option for just ignoring the point when CAMB fails (for example when Halofit fails) - that is a big issue for me now...

**Comment by vivianmiranda** [comment]
Hi

I don’t think CAMB python/cobaya is catching Halofit Takahashi errors. My CAMB was pretty much update.

Best
Vivian

On Nov 20, 2018, at 1:28 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Vivian,

There is an option for CAMB/CLASS, stop_at_error, which is False by default. If this is happening to you and you have not set this option to True manually, the reason is likely that you have found a CAMB error which is not explicitly caught by Python, either because (a) we didn't know about it, or (b) your CAMB version is not up to date. To check which one is the case, you can perform the following test:

  1.  Re-run Cobaya with debug: True, and take note of the arguments mentioned in the last line looking like [camb XXXXXXX] Setting parameters {...}.
  2.  Download an up to date version of CAMB from Git, compile it, and try to run CAMB with your parameter values; see if it fails.

If it does fail, you have found a new uncaught error, so please send us your input parameters; if it does not, this means you need to update your CAMB version (if you are using a custom version, you can download the latest Git one, and merge yours into is using something like meld<http://meldmerge.org/>). If after merging you still get the error, let us know and we'll see how to solve it.

Cheers

**Comment by JesusTorrado** [comment]
Hi Vivian,

In that case, can you tell us if there is a way for us to reproduce the error, so that we can locate the offending lines in the CAMB Python interface and wrap them in a try:except?

Or alternatively, if you prefer not to share your CAMB modification, you may want to do it yourself: locate the part of the Python interface of CAMB that fails and try to raise a `CAMBError`, which you can import to that file with `from .baseconfig import CAMBError`. `CAMBError`'s are automatically treated by Cobaya as zero-likelihood points.

**Comment by vivianmiranda** [comment]
I am not using mod CAMB

I was just running DES only chains with omega_m, omega_b parameterization and Y1 priors (I used cosmolike as the likelihood and data vector but that should not matter) - some of the param range is too extreme for Halofit so I get an “Error in Halofit”.

To avoid the problem I made the following hack on halofit_ppf

                else if (xlogr2>3.4999) then
                    !VM begins
                    ! Totally crazy non-linear
                    !global_error_flag=349
                    write(*,*) 'Error in halofit'
                    !goto 101
                    !VM ends
                end if



On Nov 20, 2018, at 10:55 PM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Vivian,

In that case, can you tell us if there is a way for us to reproduce the error, so that we can locate the offending lines in the CAMB Python interface and wrap them in a try:except?

Or alternatively, if you prefer not to share your CAMB modification, you may want to do it yourself: locate the part of the Python interface of CAMB that fails and try to raise a CAMBError, which you can import to that file with from .baseconfig import CAMBError. CAMBError's are automatically treated by Cobaya as zero-likelihood points.

**Comment by JesusTorrado** [comment]
Glad that you solved it! Closing it then.

In any case, if you send us the precise CAMB input parameters for that case (got with `debug:True` as explained above), we should be able to fix it at the Python interface level, so that you don't have to keep your own modification just for that, and no one else finds that error in the future.
