### ISSUE TITLE
Unexpected logzero behaviour

### ISSUE THREAD

**Issue by williamjameshandley** [CobayaSampler/cobaya#77]
As discussed in [this anesthetic issue](https://github.com/williamjameshandley/anesthetic/pull/71#discussion_r372246262), there is some slightly unexpected behaviour within `cobaya.samplers.polychord.polychord.polychord.run`. The return of `logpost` is:
```python
 return max(logposterior + self.logvolume, 0.99 * self.pc_settings.logzero), derived
```
I can see two potential problems with this usage:
1)  `self.logvolume`, could in theory be positive or negative. PolyChord returns `pc_settings.logzero` to indicate an unphysical parameter region, so shouldn't really be increased or decreased
2) Cobaya is effectively re-defining the logzero value to be `0.99 pc_settings.logzero`, i.e. turning the points back into 'only just physical'. This causes issues with codes that assume the `logzero` value is interpreted as unphysical regions. What is the motivation for this modification?

I'd like to understand whether there are some deeper cobaya reasons for this before submitting a PR

**Comment by JesusTorrado** [comment]
Hi @williamjameshandley 

Sorry, I've been quite busy with an application.

The 0.99 factor was there because at some point (I think prior to 1.16) PolyChord was not able to take into account "unphysical" regions of priors, e.g. to guess that in the x,y plane for x,y in [0,1], if we assign -inf to the cases with x<y, the resulting evidence should be 1/2 and not one. SInce that's not the case any more, I will remove the 0.99 factor in devel (2.1, to be released quite soon).

Re the logvolume, as you pointed out in the [anesthetic issue](https://github.com/williamjameshandley/anesthetic/pull/71), it's undoing a scale transformation previously applied, so it returns the correct evidence. Indeed, instead of renormalising the prior **density** to [0,1] using `pc_prior` and then passing the pure likelihood, I am using `pc_prior` to just renormalise with respect to the bounds, and pass the *density*-part of the priors together with the likelihood. This way, we can allow for 1d priors for which we don't have an automatic renormalisation to [0,1].

I hope that clarifies it. Thanks again and sorry for the delay!

**Comment by williamjameshandley** [comment]
> The 0.99 factor was there because at some point (I think prior to 1.16) PolyChord was not able to take into account "unphysical" regions of priors, e.g. to guess that in the x,y plane for x,y in [0,1], if we assign -inf to the cases with x<y, the resulting evidence should be 1/2 and not one.

I think this must be some kind of past misunderstanding, since both PolyChord and MultiNest have always been able to take into account unphysical regions of priors in the manner you describe above (I've been doing this in cosmomc+camb since 2014, which have quite large unphysical regions in comparison with montepython+class) -- it's baked in by design from how the codes interpret values `<=logzero`. 

Regardless, it looks like this should fix the issue. Many thanks

**Comment by williamjameshandley** [comment]
Ah, hang on, I misread the above. The default behaviour of both MultiNest & PolyChord is to treat logzero regions as unphysical and therefore 'prior excluded', i.e. in the example you describe above the evidence should be 1. This may not be the behaviour you desire, but it is the behaviour for all nested sampling algorithms.

**Comment by williamjameshandley** [comment]
You can of course 'undo' this effect very easily by sampling from the prior and recording the number of rejected points. I think the latest version of PolyChord provides this information in a `.prior_info` file (although it's not very intuitively named).

**Comment by JesusTorrado** [comment]
Thanks for the clarification! I will look into it and try to do it the proper way, instead of my ugly hack.

**Comment by JesusTorrado** [comment]
Hi @williamjameshandley 

I am back to fixing this. So, from reading the code, I reckon `ndiscarded` is the *total* number of posterior evaluations during the generation of the initial live set, including *both* good and discarded points, right?

**Comment by williamjameshandley** [comment]
Yes : )

**Comment by JesusTorrado** [comment]
Great, thanks!

I'll try to fix this for the next release, which is coming very soon with loads of changes. We are still pulling 1.16, so if there are any changes since then that would grant a 1.17 release, we'd be happy to upgrade.

**Comment by JesusTorrado** [comment]
f056f5c takes care of this, and there is a note in the `devel` branch documentation about increasing `nprior` if there are unphysical regions.

Thanks, @williamjameshandley !

**Comment by williamjameshandley** [comment]
>I'll try to fix this for the next release, which is coming very soon with loads of changes. We are still pulling 1.16, so if there are any changes since then that would grant a 1.17 release, we'd be happy to upgrade.

Hi @JesusTorrado . What timescale is the next release? I may want to put in a PR soon adjusting the default fast-slow behaviour, which is a little too conservative and therefore resulting in very long run times out-of-the-box.

**Comment by JesusTorrado** [comment]
Sounds very interesting!

The next release should happen in at most a few weeks; one to two in the best case scenario.
