### ISSUE TITLE
scale-dependent growth rate

### ISSUE THREAD

**Issue by sjoudaki** [CobayaSampler/cobaya#97]
Hi Antony and Jesus,

Currently it seems Cobaya returns get_fsigma8 and get_sigma_R, such that the redshift-dependent growth rate can be obtained from their ratio. However, as the growth rate is also scale dependent in certain cosmologies (e.g. in modified gravity theories), have you perhaps considered the possibility for Cobaya to return a growth rate that is both redshift and scale dependent? (e.g. within the existing framework where get_fsigma8 returns a scale-dependent quantity)? Alternatively, if Cobaya directly returns the matter density perturbation \delta(k,z) that would be useful too.

Thanks,
Shahab

**Comment by cmbant** [comment]
You could use the get_sigma_R function twice: since it has a var_pair argument, you could use it to get the velocity-density cross result as well as the standard sigma_R, and combine them to get analogous of fsigma8. Whether or not that would be closely related to what the experiment is actually measuring is of course a separate matter - do you have a case where fsigma(R) is clearly useful?

You can get any result you like from CAMB by requesting "CAMBdata" and using self.provider.get_CAMBdata() and then using the CAMB result object to get what you want.

**Comment by sjoudaki** [comment]
Thank you so much for your reply Antony! Yes, we were thinking of the growth rate f(k,z) in the context of redshift-space galaxy clustering. It seems get_sigma_R could indeed be used to obtain f(z), but not f(k,z). [please note I only mentioned get_sigma_R with R = 8 Mpc/h to isolate the growth rate f from get_fsigma8, as there seems to be no explicit sigma8(z) function in Cobaya] But I will have a look at CAMBdata, that seems like it could indeed be what we need. Out of curiosity, does the equivalent to CAMBdata also exist for CLASS? (as we would want compatibility with both Boltzmann codes)

**Comment by cmbant** [comment]
You could use get_sigma_R to get fsigma_R(z), analogous to how we defined fsigma8 in the Planck params but generalizing to different scales R. 

You could of course also use the matter power spectrum P(k,z) to infer the growth [for whatever variables of interest;  probably best to use the velocity power and cross spectrum directly since that's more closely related to what is actual measured by redshift surveys]

There's no Class equivalent of CAMBdata at the moment.

**Comment by sjoudaki** [comment]
Ok, thanks Antony! Generalizing to different scales R would indeed allow for some scale-dependence to be captured, but not exactly the quantity that I would want, and I agree that the matter power spectrum could be used to obtain the growth function (and the growth rate through its logarithmic derivative). Asking directly for the velocity and cross spectra might be the most useful though, thanks!
